### ISSUE TITLE
new URL for get_chelsa function

### ISSUE THREAD

**Issue by micdimu** [mbertolacci/climatedata#1]
Dear Bertolacci,
get_chelsa function does not work. The URL seems disappeared, I'have modified your function by changing "ftp://envidatrepo.wsl.ch/uploads/chelsa/chelsa_V1/" the old one with the newest URL "ftp://envicloud.wsl.ch/chelsa/chelsa_V1/". Now it works both for current and future scenarios.
Could you please update your function.
Cheers,
Michele

**Comment by mbertolacci** [comment]
Hi @micdimu. I think this issue is meant for the [mirzacengic/climatedata](https://github.com/MirzaCengic/climatedata/) R package, not this one. Unfortunately, they have the same name! There is no function with the name you suggest here.
