### ISSUE TITLE
Error in strsplit(iod_data_raw$Date, ":") : non-character argument

### ISSUE THREAD

**Issue by urskalbitzer** [mbertolacci/climatedata#2]
Hi,
I am trying to download IOD data into R and came across your package. However, I was not able to download the data. When I run `climatedata::load_iod()` I get the error message:

`Error in strsplit(iod_data_raw$Date, ":") : non-character argument`

Is there any chance that you find the time to fix this error?

Thanks!

**Comment by mbertolacci** [comment]
Thanks for this report. It looks as though [JAMSTEC](http://www.jamstec.go.jp/frcgc/research/d1/iod/e/iod/about_iod.html), the old source for these data, is not working. [NOAA](https://psl.noaa.gov/gcos_wgsp/Timeseries/DMI/) has an alternative source. I have updated the package to support NOAA as the default source for now, so if you update and try again it ought to work.

**Comment by urskalbitzer** [comment]
Thanks for fixing this so quickly. It works for me now.
